; === ESP32 classic ===
[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.3

; === ESP32-S3 ===
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^6.21.3

; === ESP32-C3 Super Mini ===
[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 160000000L ; 160 MHz for better WiFi signal strength
; ArduinoJson не нужен — C3 использует бинарный протокол
